import { env } from "./env";

export interface MonitorTarget {
  id: string;
  name: string;
  type: "ping" | "https" | "mysql" | "postgres" | "mongodb" | "redis" | "ssl" | "backup";
  host?: string;
  url?: string;
  port?: number;
  timeout?: number;
  method?: string;
  expectedStatusCode?: number;
  warningDays?: number;
  criticalDays?: number;
  access_key?: string;
  secret_key?: string;
  prefix?: string;
  bucket?: string;
  maxBackupAgeHours?: number;
  database?: string;
  username?: string;
  password?: string;
  connectionString?: string;
}

export const config = {
  servers: [
    {
      id: "compresspdf.to, api.compresspdf.to, bmc, wcc, softekocms.com",
      name: "Server:2- 31.220.20.42",
      host: "31.220.20.42",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "invoicegenerator.biz, api.invoicegenerator.biz, monitoring.softekocms.com",
      name: "Server:3- 31.220.73.42",
      host: "31.220.73.42",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "redmine.softeko.co",
      name: "Server:4- 154.38.184.59",
      host: "154.38.184.59",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "staging servers",
      name: "Server:5- 212.28.189.176",
      host: "212.28.189.176",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "gitlabce.softekocms.com",
      name: "Server:6- 207.244.246.116",
      host: "207.244.246.116",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "onlinegradecalculator.io, aiaxio.com, r2.aiaxio.com, api.aiaxio.com",
      name: "Server:7- 82.29.155.149",
      host: "82.29.155.149",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "CL>> pqsjapan.jp",
      name: "Server:8- 147.93.45.67",
      host: "147.93.45.67",
      type: "ping",
      timeout: 5000,
    },
    {
      id: "CL>> dev.pqsjapan.jp",
      name: "Server:9- 185.199.52.126",
      host: "185.199.52.126",
      type: "ping",
      timeout: 5000,
    },
  ] as MonitorTarget[],

  applications: [
    {
      id: "app-1",
      name: "api.aiaxio.com",
      url: "https://api.aiaxio.com",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-2",
      name: "softekocms.com",
      url: "https://softekocms.com/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-3",
      name: "business-model-canvas.io",
      url: "https://business-model-canvas.io/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-4",
      name: "websitecostcalculator.io",
      url: "https://websitecostcalculator.io/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-5",
      name: "compresspdf.to",
      url: "https://compresspdf.to/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-6",
      name: "api.compresspdf.to",
      url: "https://api.compresspdf.to/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-7",
      name: "invoicegenerator.biz",
      url: "https://invoicegenerator.biz/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-8",
      name: "redmine.softeko.co",
      url: "https://redmine.softeko.co/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-9",
      name: "gitlabce.softekocms.com",
      url: "https://gitlabce.softekocms.com/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-10",
      name: "onlinegradecalculator.io",
      url: "https://onlinegradecalculator.io/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-11",
      name: "shastokotha.com",
      url: "https://shastokotha.com/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-12",
      name: "aiaxio.com",
      url: "https://aiaxio.com/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-13",
      name: "r2apis.softekocms.com",
      url: "https://r2apis.softekocms.com/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-14",
      name: "pqsjapan.jp",
      url: "https://pqsjapan.jp/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-15",
      name: "dev.pqsjapan.jp",
      url: "https://dev.pqsjapan.jp/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
    {
      id: "app-16",
      name: "staging.pqsjapan.jp",
      url: "https://staging.pqsjapan.jp/",
      type: "https",
      method: "GET",
      timeout: 10000,
      expectedStatusCode: 200,
    },
  ] as MonitorTarget[],

  databases: [] as MonitorTarget[],

  sslCertificates: [
    {
      id: "ssl-1",
      name: "AI Axio API SSL",
      host: "api.aiaxio.com",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-2",
      name: "SoftekoCMS SSL",
      host: "softekocms.com",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-3",
      name: "Business Model Canvas SSL",
      host: "business-model-canvas.io",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-4",
      name: "Website Cost Calculator SSL",
      host: "websitecostcalculator.io",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-7",
      name: "Invoice Generator SSL",
      host: "invoicegenerator.biz",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-8",
      name: "Redmine Softeko SSL",
      host: "redmine.softeko.co",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-9",
      name: "GitLab CE SoftekoCMS SSL",
      host: "gitlabce.softekocms.com",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-10",
      name: "Online Grade Calculator SSL",
      host: "onlinegradecalculator.io",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-11",
      name: "Shastokotha SSL",
      host: "shastokotha.com",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-12",
      name: "AI Axio SSL",
      host: "aiaxio.com",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-13",
      name: "R2 APIs SSL",
      host: "r2apis.softekocms.com",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-14",
      name: "Dev PQS Japan SSL",
      host: "dev.pqsjapan.jp",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-15",
      name: "Staging PQS Japan SSL",
      host: "staging.pqsjapan.jp",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
    {
      id: "ssl-16",
      name: "PQS Japan SSL",
      host: "pqsjapan.jp",
      port: 443,
      type: "ssl",
      timeout: 10000,
      warningDays: 30,
      criticalDays: 7,
    },
  ] as MonitorTarget[],

  backups: [
    {
      id: "backup-1",
      name: "GitLab Backups",
      type: "backup",
      url: "https://r2.aiaxio.com/api/v1/files",
      access_key: "28a7cfd881e5ee55f6a1395d04cef998",
      secret_key:
        "373e6f501a18474d3588577429d41ebe7ce5c561cca8e30c3d6eddd53845b676",
      prefix: "gitlab-backups",
      bucket: "gitlab",
      maxBackupAgeHours: 1,
      timeout: 10000,
    },
    {
      id: "backup-2",
      name: "GitLab Backups",
      type: "backup",
      url: "https://r2.aiaxio.com/api/v1/files",
      access_key: "28a7cfd881e5ee55f6a1395d04cef998",
      secret_key:
        "373e6f501a18474d3588577429d41ebe7ce5c561cca8e30c3d6eddd53845b676",
      prefix: "gitlab-backups",
      bucket: "gitlab",
      maxBackupAgeHours: 1,
      timeout: 10000,
    },
  ] as MonitorTarget[],
};
